"""
This type stub file was generated by pyright.
"""

import importlib.metadata

"""
This module provides the main entry point for the autogen_agentchat package.
It includes logger names for trace and event logs, and retrieves the package version.
"""
TRACE_LOGGER_NAME = ...
EVENT_LOGGER_NAME = ...
__version__ = ...
