[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "scribe for You"
version = "0.1.0"
description = "Your AI-Powered Book Writing Assistant"
readme = "README.md"
requires-python = ">=3.8"

[tool.ruff.lint]
# Enable Pyflakes (F), pycodestyle (E, W), and isort (I)
select = ["E", "F", "W", "I"]

[tool.ruff.format]
# Use double quotes for strings.
quote-style = "double"