"""
This type stub file was generated by pyright.
"""

from ._states import AssistantAgentState, BaseGroupChatManagerState, BaseState, ChatAgentContainerState, MagenticOneOrchestratorState, RoundRobinManagerState, SelectorManagerState, SocietyOfMindAgentState, SwarmManagerState, TeamState

"""State management for agents, teams and termination conditions."""
__all__ = ["BaseState", "AssistantAgentState", "BaseGroupChatManagerState", "ChatAgentContainerState", "RoundRobinManagerState", "SelectorManagerState", "SwarmManagerState", "MagenticOneOrchestratorState", "TeamState", "SocietyOfMindAgentState"]
