"""
This type stub file was generated by pyright.
"""

from ._terminations import ExternalTermination, FunctionCallTermination, FunctionalTermination, HandoffTermination, MaxMessageTermination, SourceMatchTermination, StopMessageTermination, TextMentionTermination, TextMessageTermination, TimeoutTermination, TokenUsageTermination

"""
This module provides various termination conditions for controlling the behavior of
multi-agent teams.
"""
__all__ = ["MaxMessageTermination", "TextMentionTermination", "StopMessageTermination", "TokenUsageTermination", "HandoffTermination", "TimeoutTermination", "ExternalTermination", "SourceMatchTermination", "TextMessageTermination", "FunctionCallTermination", "FunctionalTermination"]
