"""
This type stub file was generated by pyright.
"""

import traceback
from typing import List
from pydantic import BaseModel, SerializeAsAny
from ...base import Response, TaskResult
from ...messages import BaseAgentEvent, BaseChatMessage, StopMessage

class SerializableException(BaseModel):
    """A serializable exception."""
    error_type: str
    error_message: str
    traceback: str | None = ...
    @classmethod
    def from_exception(cls, exc: Exception) -> SerializableException:
        """Create a GroupChatError from an exception."""
        ...
    
    def __str__(self) -> str:
        """Return a string representation of the error, including the traceback if available."""
        ...
    


class GroupChatStart(BaseModel):
    """A request to start a group chat."""
    messages: List[SerializeAsAny[BaseChatMessage]] | None = ...
    output_task_messages: bool = ...


class GroupChatAgentResponse(BaseModel):
    """A response published to a group chat."""
    response: SerializeAsAny[Response]
    name: str
    ...


class GroupChatTeamResponse(BaseModel):
    """A response published to a group chat from a team."""
    result: SerializeAsAny[TaskResult]
    name: str
    ...


class GroupChatRequestPublish(BaseModel):
    """A request to publish a message to a group chat."""
    ...


class GroupChatMessage(BaseModel):
    """A message from a group chat."""
    message: SerializeAsAny[BaseAgentEvent | BaseChatMessage]
    ...


class GroupChatTermination(BaseModel):
    """A message indicating that a group chat has terminated."""
    message: StopMessage
    error: SerializableException | None = ...


class GroupChatReset(BaseModel):
    """A request to reset the agents in the group chat."""
    ...


class GroupChatPause(BaseModel):
    """A request to pause the group chat."""
    ...


class GroupChatResume(BaseModel):
    """A request to resume the group chat."""
    ...


class GroupChatError(BaseModel):
    """A message indicating that an error occurred in the group chat."""
    error: SerializableException
    ...
