"""
This type stub file was generated by pyright.
"""

from typing import List, Union
from autogen_core import FunctionCall, Image
from autogen_core.models import FunctionExecutionResult, LLMMessage
from pydantic import BaseModel

_StructuredContent = BaseModel
_UserContent = Union[str, List[Union[str, Image]]]
_AssistantContent = Union[str, List[FunctionCall]]
_FunctionExecutionContent = List[FunctionExecutionResult]
_SystemContent = str
def content_to_str(content: _UserContent | _AssistantContent | _FunctionExecutionContent | _SystemContent | _StructuredContent) -> str:
    """Convert the content of an LLMMessage to a string."""
    ...

def remove_images(messages: List[LLMMessage]) -> List[LLMMessage]:
    """Remove images from a list of LLMMessages"""
    ...
