layers:
  - name: "Title"
    text: "Final Brochure"
    font: "Arial"
    size: 32
    color: "#000000"
  - name: "Subtitle"
    text: "Automated via Script"
    font: "Helvetica"
    size: 20
    color: "#333333"
