"""
This type stub file was generated by pyright.
"""

from typing import Any, Dict
from autogen_core.tools import BaseTool
from pydantic import BaseModel, model_validator

event_logger = ...
class Handoff(BaseModel):
    """Handoff configuration."""
    target: str
    description: str = ...
    name: str = ...
    message: str = ...
    @model_validator(mode="before")
    @classmethod
    def set_defaults(cls, values: Dict[str, Any]) -> Dict[str, Any]:
        ...
    
    @property
    def handoff_tool(self) -> BaseTool[BaseModel, BaseModel]:
        """Create a handoff tool from this handoff configuration."""
        ...
    
