"""
This type stub file was generated by pyright.
"""

import asyncio
from typing import Any, List, Mapping, Sequence
from autogen_core import MessageContext, event, rpc
from autogen_core.models import ChatCompletionClient
from ....base import TerminationCondition
from ....messages import BaseAgentEvent, BaseChatMessage, MessageFactory
from .._base_group_chat_manager import BaseGroupChatManager
from .._events import GroupChatAgentResponse, GroupChatStart, GroupChatTeamResponse, GroupChatTermination

trace_logger = ...
class MagenticOneOrchestrator(BaseGroupChatManager):
    """The MagenticOneOrchestrator manages a group chat with ledger based orchestration."""
    def __init__(self, name: str, group_topic_type: str, output_topic_type: str, participant_topic_types: List[str], participant_names: List[str], participant_descriptions: List[str], max_turns: int | None, message_factory: MessageFactory, model_client: ChatCompletionClient, max_stalls: int, final_answer_prompt: str, output_message_queue: asyncio.Queue[BaseAgentEvent | BaseChatMessage | GroupChatTermination], termination_condition: TerminationCondition | None, emit_team_events: bool) -> None:
        ...
    
    @rpc
    async def handle_start(self, message: GroupChatStart, ctx: MessageContext) -> None:
        """Handle the start of a task."""
        ...
    
    @event
    async def handle_agent_response(self, message: GroupChatAgentResponse | GroupChatTeamResponse, ctx: MessageContext) -> None:
        ...
    
    async def validate_group_state(self, messages: List[BaseChatMessage] | None) -> None:
        ...
    
    async def save_state(self) -> Mapping[str, Any]:
        ...
    
    async def load_state(self, state: Mapping[str, Any]) -> None:
        ...
    
    async def select_speaker(self, thread: Sequence[BaseAgentEvent | BaseChatMessage]) -> List[str] | str:
        """Not used in this orchestrator, we select next speaker in _orchestrate_step."""
        ...
    
    async def reset(self) -> None:
        """Reset the group chat manager."""
        ...
    
