# .github/workflows/deploy.yml
name: Deploy Docusaurus to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    concurrency:
      group: "pages"
      cancel-in-progress: false

    # This default is still correct for your 'run' steps (npm install, npm build)
    defaults:
      run:
        working-directory: ./docs

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'
        cache: 'npm'
        # FIX: Provide the full path to the lock file from the repository root
        cache-dependency-path: docs/package-lock.json

    - name: Install dependencies
      # This runs in './docs' because of the 'defaults' setting
      run: npm install

    - name: Build website
      # This also runs in './docs'
      run: npm run build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        # This path is relative to the REPOSITORY root, so it's correct
        publish_dir: ./docs/build
