name: Build Documentation

on:
  pull_request:
    paths:
      - 'docs/**'
      - '.github/workflows/docs.yml'

permissions:
  contents: read

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Build docs
        run: |
          ./scripts/build_docs.sh
